// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"mall/app/user/rpc/internal/logic"
	"mall/app/user/rpc/internal/svc"
	"mall/app/user/rpc/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// 登录
func (s *UserServer) Login(ctx context.Context, in *pb.LoginRequest) (*pb.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// 注册
func (s *UserServer) Register(ctx context.Context, in *pb.RegisterRequest) (*pb.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

// 获取用户信息
func (s *UserServer) UserInfo(ctx context.Context, in *pb.UserInfoRequest) (*pb.UserInfoResponse, error) {
	l := logic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}

// 添加收货地址
func (s *UserServer) AddUserAddress(ctx context.Context, in *pb.UserAddressAddReq) (*pb.UserAddressAddResp, error) {
	l := logic.NewAddUserAddressLogic(ctx, s.svcCtx)
	return l.AddUserAddress(in)
}

// 编辑收货地址
func (s *UserServer) EditUserAddress(ctx context.Context, in *pb.UserAddressEditReq) (*pb.UserAddressEditResp, error) {
	l := logic.NewEditUserAddressLogic(ctx, s.svcCtx)
	return l.EditUserAddress(in)
}

// 删除收货地址
func (s *UserServer) DelUserAddress(ctx context.Context, in *pb.UserAddressDelReq) (*pb.UserAddressDelResp, error) {
	l := logic.NewDelUserAddressLogic(ctx, s.svcCtx)
	return l.DelUserAddress(in)
}

// 获取收货地址列表
func (s *UserServer) GetUserAddressList(ctx context.Context, in *pb.UserAddressListReq) (*pb.UserAddressListResp, error) {
	l := logic.NewGetUserAddressListLogic(ctx, s.svcCtx)
	return l.GetUserAddressList(in)
}

// 添加收藏
func (s *UserServer) AddUserCollection(ctx context.Context, in *pb.UserCollectionAddReq) (*pb.UserCollectionAddResp, error) {
	l := logic.NewAddUserCollectionLogic(ctx, s.svcCtx)
	return l.AddUserCollection(in)
}

// 删除收藏
func (s *UserServer) DelUserCollection(ctx context.Context, in *pb.UserCollectionDelReq) (*pb.UserCollectionDelResp, error) {
	l := logic.NewDelUserCollectionLogic(ctx, s.svcCtx)
	return l.DelUserCollection(in)
}

// 收藏列表
func (s *UserServer) GetUserCollectionList(ctx context.Context, in *pb.UserCollectionListReq) (*pb.UserCollectionListResp, error) {
	l := logic.NewGetUserCollectionListLogic(ctx, s.svcCtx)
	return l.GetUserCollectionList(in)
}

// 根据主键id,查询收货地址
func (s *UserServer) GetUserAddressInfo(ctx context.Context, in *pb.UserAddressInfoReq) (*pb.UserAddress, error) {
	l := logic.NewGetUserAddressInfoLogic(ctx, s.svcCtx)
	return l.GetUserAddressInfo(in)
}
