// Code generated by goctl. DO NOT EDIT.
package types

type UserAddress struct {
	Id            int64  `json:"id"`
	Uid           uint64 `json:"uid"`            //用户id
	Name          string `json:"name"`           //收货人名称
	Phone         string `json:"phone"`          //手机号
	IsDefault     int32  `json:"is_default"`     //是否为默认地址
	PostCode      string `json:"post_code"`      //邮政编码
	Province      string `json:"province"`       //省份/直辖市
	City          string `json:"city"`           //城市
	Region        string `json:"region"`         //区
	DetailAddress string `json:"detail_address"` //详细地址(街道)
	CreateTime    int64  `json:"create_time"`    //数据创建时间[禁止在代码中赋值]
	UpdateTime    int64  `json:"update_time"`    //数据更新时间[禁止在代码中赋值]
}

type UserAddressListReq struct {
}

type UserAddressListRes struct {
	List []UserAddress `json:"list"`
}

type UserAddressAddReq struct {
	Name          string `json:"name"`           //收货人名称
	Phone         string `json:"phone"`          //手机号
	IsDefault     int32  `json:"is_default"`     //是否为默认地址
	PostCode      string `json:"post_code"`      //邮政编码
	Province      string `json:"province"`       //省份/直辖市
	City          string `json:"city"`           //城市
	Region        string `json:"region"`         //区
	DetailAddress string `json:"detail_address"` //详细地址(街道)
}

type UserAddressAddRes struct {
}

type UserAddressEditReq struct {
	Id            int64  `json:"id"`
	Name          string `json:"name"`           //收货人名称
	Phone         string `json:"phone"`          //手机号
	IsDefault     int32  `json:"is_default"`     //是否为默认地址
	PostCode      string `json:"post_code"`      //邮政编码
	Province      string `json:"province"`       //省份/直辖市
	City          string `json:"city"`           //城市
	Region        string `json:"region"`         //区
	DetailAddress string `json:"detail_address"` //详细地址(街道)
}

type UserAddressEditRes struct {
}

type UserAddressDelReq struct {
	Id int64 `json:"id"`
}

type UserAddressDelRes struct {
}

type UserInfo struct {
	Id         uint64 `json:"id"`          //用户ID
	Username   string `json:"username"`    //用户名
	Phone      string `json:"phone"`       //手机号
	CreateTime int64  `json:"create_time"` //创建时间
	UpdateTime int64  `json:"update_time"` //更新时间
}

type LoginReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type RegisterReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
	Username string `json:"username"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	UserInfo UserInfo `json:"userInfo"`
}

type UserCollectionAddReq struct {
	ProductId int64 `json:"product_id"` // 商品id
}

type UserCollectionAddRes struct {
}

type UserCollectionDelReq struct {
	Id int64 `json:"id"` // 收藏Id
}

type UserCollectionDelRes struct {
}

type UserCollectionListReq struct {
}

type UserCollectionListRes struct {
	ProductId []int64 `json:"product_id"` // 商品id
}
